title: 'Mehdi Massoudi'
description: "Learn more about the developer everyone is raving about. Find your next product or employee here."
baseurl: "/"
url: "https://mehdimas.github.io"

header_pages:
  - index.md
  - notes.md
  - resume.md

style: dark

plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

footer: |
  follow me on <a href="https://twitter.com/MrMassoudi">Twitter</a></br/>
  connect with me on <a href="https://www.linkedin.com/in/mehdi-massoudi-ab140836/">LinkedIn</a>

google_analytics: UA-142499902-1